### ISSUE TITLE
Document how to create a GitHub "bot" user for commenting

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#13]
1. Create a GitHub Tugboat user
1. Grant that user access to your GitHub repo
1. Generate a token for that user
1. Log back into GitHub with your personal account
1. While on the Tugboat Dashboard for the Repository, click Repository Settings
1. Scroll down almost to the bottom until you see GitHub Comments
1. Click the Change button and add your GitHub Tugboat token there

**Comment by bchavet** [comment]
https://docs.tugboat.qa/concepts/repositories/#provider-integrations
