### ISSUE TITLE
Include "approval" steps on CLI installation instructions for Mac

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#151]
After upgrading to Catalina, my `tugboat` cli would no longer work. I got a message saying `cannot be opened because the developer cannot be verified.`. After searching the web, I found this issue and followed the instructions there to get my cli working again: https://github.com/hashicorp/terraform/issues/23033#issuecomment-539736692

**Comment by dacharyc** [comment]
Oof, I missed this entirely and haven't tried to use the `tugboat` cli since the Catalina update. Thanks, James!
