### ISSUE TITLE
Improve Drupal 8 example and associated config.yml

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#21]
1. Our Drupal 8 Makefile doesn’t fix permissions on the file directories
2. Private files and exported config are typically stored outside the webroot. Since the webroot is a symlink, that can get funky.
3. IIRC, our D8 Makefile didn’t have `composer install` in the build target

We also should make sure that our Drupal 8 example tugboat project uses the same Makefile.

**Comment by bchavet** [comment]
s/Makefile/config.yml/g

**Comment by bchavet** [comment]
Did #157 address this?

**Comment by q0rban** [comment]
I had forgotten about this. 😆 Looks like I missed #2. I'll add that.
