### ISSUE TITLE
Add a page about using Diffy with Tugboat

### ISSUE THREAD

**Issue by dacharyc** [TugboatQA/docs#218]
We're working on some new functionality that will enable Tugboat to run commands after a Preview is done building.

This will enable Tugboat to easily integrate with Diffy, and start a Diffy screenshot diff against a Tugboat Preview environment after the build has finished.

The basics will be 
1. Set up some envvars in Tugboat for the Diffy API key and Diffy Project ID
1. Install & auth the Diffy CLI during the Preview's `init` phase 
2. Compare after the preview has built.

Add a page to the documentation site about using this integration with Diffy. Consider whether it's just a code snippet, or whether it's a tutorial covering the Diffy steps.

**Comment by q0rban** [comment]
Should #226 have closed this?

**Comment by dacharyc** [comment]
Yup! Closed by #226 .
