### ISSUE TITLE
Document how to authenticate to a GitHub Repo using a token

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#239]
Sometimes organization-level admin access is needed for certain GitHub repos, and that can be challenging to get. We have a workaround using GitHub tokens. Technical details are [here](https://gist.github.com/bchavet/eeaf19487d0e9b76eb53a660d9cec160), but it would be nice to document this in a digestible How To.

**Comment by dacharyc** [comment]
I think I missed this issue when making the PR, @q0rban - should this be closed by the PR we merged recently?

https://github.com/TugboatQA/docs/pull/244/

**Comment by q0rban** [comment]
Closed in #244
