### ISSUE TITLE
Add `$DOCROOT` to environment variables

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#261]
@mherchel went to Tugboat documentation, searched for variables, went to 'Environment Variables' and couldn't find any documentation on the `$DOCROOT` environment variable. I mentioned that that environment variable is only present on images that have a web server installed, such as Apache or Nginx. He suggested that the variable be listed there with an asterisk stating that it's only available on certain images, so that it's more easily findable.

**Comment by dacharyc** [comment]
There's a page on setting this: https://docs.tugboat.qa/setting-up-services/how-to-set-up-services/set-the-document-root-path/

Is there another place you or Mike would like to see this, @q0rban ?

**Comment by mherchel** [comment]
My workflow was that I went looking for variables, so I went to that page within the docs. Then I hit CMD+F, and searched for docroot. I would expect all variables to be listed on that page 🤷‍♂️

**Comment by bchavet** [comment]
Hmm, this is a tough one. The `$DOCROOT` variable doesn't come from Tugboat, it comes from the Docker image. But, I can see why someone would look for it on the environment variable page.

Maybe we could add a section to the envvar reference page to address variables that come from the Docker images. We can list the variables that we manage for our images, and add an explanation about how there may be other variables available, depending on the image used, but that is out of our control.

**Comment by mherchel** [comment]
Yeah, as someone who's not familiar w docker, I'm expecting all the variables to be listed on this page. Maybe have a section called "Variables provided by the docker image" and then list common ones (like docroot) and then have a note that these variables are out of our control, and maybe also provide a link to some docker documentation on them?

**Comment by q0rban** [comment]
I think given this DOCROOT variable is:

1. Added by us (not something that ships with the official Dockerfile)
2. Referenced often in various starter configs, snippets, and articles
3. Something Mike instinctively looked for on the Env. Variables documentation

That having it on our list of environment variables could be helpful to others as well.

**Comment by q0rban** [comment]
> Maybe we could add a section to the envvar reference page to address variables that come from the Docker images. We can list the variables that we manage for our images, and add an explanation about how there may be other variables available, depending on the image used, but that is out of our control.

I like this suggestion ^^
