### ISSUE TITLE
Improve Tugboat + Pantheon documentation

### ISSUE THREAD

**Issue by jcnventura** [TugboatQA/docs#295]
Thanks for providing the docs for Pantheon integration in https://docs.tugboat.qa/starter-configs/tutorials/pantheon.

I've run across a pair of problems:

1. While installing terminus, the documented installer uses composer which ends up with a fatal error due to running out of memory.
So instead of:
```
        # Install the latest version of terminus
        - wget -O /tmp/installer.phar https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar
        - php /tmp/installer.phar install
```

I suggest the use of the following standalone terminus install (from https://pantheon.io/docs/terminus/install#standalone-terminus-phar)
```
        # Install the latest version of terminus
        - |
          cat > /tmp/install_terminus.sh << 'TERMINUS'
          #!/bin/bash
          curl -L https://github.com/pantheon-systems/terminus/releases/download/$(curl --silent "https://api.github.com/repos/pantheon-systems/terminus/releases/latest" | perl -nle'print $& while m{"tag_name": "\K.*?(?=")}g')/terminus.phar --output /usr/local/bin/terminus
          chmod +x /usr/local/bin/terminus
          TERMINUS
        - chmod +x /tmp/install_terminus.sh && /tmp/install_terminus.sh
```
The heredoc syntax is necessary because Tugboat's Yaml parser has an issue with the perl parameters in this call.

2. The files synchronized from Pantheon will be owned by the root user. To fix this, a final step is necessary after the rsync av command:
```
- chown -R www-data:www-data "${DOCROOT}/sites/default/files/"
```

**Comment by alphex** [comment]
This solved a terminus install problem I was having also.
