### ISSUE TITLE
Solr instructions do not work with newer versions of the solr image

### ISSUE THREAD

**Issue by johnzzon** [TugboatQA/docs#341]
When using tugboatqa/solr:8 (which I think is 8.11.2 at the time of writing), the instructions documented on https://docs.tugboatqa.com/reference/tugboat-images/#solr does not work.

It's specifically the command:
```
su -s /bin/sh -c "solr create_core -c [CORE] -force" solr
```
which generates an error "solr not found"

When debugging this it seems the solr user does not have `solr` in its $PATH. Using the absolute path to the solr binary works.

**Comment by q0rban** [comment]
Thanks for reporting this, @johnzzon ! Do you happen to know what the absolute path to the solr binary is, so we can create a PR to get this fixed?

**Comment by johnzzon** [comment]
Sure, the binary was at `/opt/solr/bin/solr`.

**Comment by q0rban** [comment]
@johnzzon I've got a PR here: #346 , does this look like the correct fix?
