### ISSUE TITLE
Update docs on how to install nodejs using nodesource

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#368]
The previous method of using nodesource install scripts to install specific versions of nodejs is no longer supported. Our [documentation](https://docs.tugboatqa.com/starter-configs/code-snippets/install-nodejs/
) should updated to match the new installation instructions:

https://github.com/nodesource/distributions#installation-instructions

**Comment by q0rban** [comment]
@rabbitlair since you've worked on this recently, would you like to try your hand at updating these docs?

**Comment by rabbitlair** [comment]
Sure thing!
