### ISSUE TITLE
Search filters only working for admin role

### ISSUE THREAD

**Issue by stefanweber** [TugboatQA/docs#380]
The quick search filters on repository overview are only visible for users with the admin role. This makes no sense. 
On the project level, the filter is available to users with the user role too, this makes sense.

**Comment by rabbitlair** [comment]
Hi @stefanweber, thank you for reporting the issue. I am sorry this is happening. I will create an internal ticket for our team to fix the problem as soon as possible.

**Comment by q0rban** [comment]
@stefanweber we're going to close this issue here. We've opened a ticket internally for this and have prioritized it. We'll let you know when the fix is deployed. Thank you for reporting it!

**Comment by stefanweber** [comment]
> @stefanweber we're going to close this issue here. We've opened a ticket internally for this and have prioritized it. We'll let you know when the fix is deployed. Thank you for reporting it!

Tanks!
