### ISSUE TITLE
index.md links don't work

### ISSUE THREAD

**Issue by mettamatt** [TugboatQA/docs#7]
Any URL that links to `index.md` doesn't open on docs.tugboat.qa

There are a couple URLs to test on this page here:

https://docs.tugboat.qa/getting-started/create-a-preview/

**Comment by q0rban** [comment]
It looks like there's a bunch of broken links. I'm guessing something structurally changed? We should add a link checker to the build process. I looked around for something and found the html-validator-cli npm project, but it doesn't seem to detect broken links, and doesn't crawl. :/

**Comment by q0rban** [comment]
https://www.digitalocean.com/community/tutorials/how-to-find-broken-links-on-your-website-using-wget-on-debian-7

**Comment by bchavet** [comment]
this looks like a winner: https://www.npmjs.com/package/broken-link-checker-local
