### ISSUE TITLE
Missing Google search results do not have redirects

### ISSUE THREAD

**Issue by q0rban** [TugboatQA/docs#79]
Sometimes I use Google to find docs, and several times recently I've searched for something on Google and gotten a 404:

![tugboat cli - Google Search 2019-06-24 22-23-01](https://user-images.githubusercontent.com/66118/60064508-a1977d80-96ce-11e9-953f-e4704d6e0157.jpg)

![site:docs tugboat qa php memory - Google Search 2019-06-24 22-24-34](https://user-images.githubusercontent.com/66118/60064574-de637480-96ce-11e9-8c6f-e8ee93ccb4ea.jpg)

**Comment by mettamatt** [comment]
Thanks, James. This is helpful! 
Is there a way to get a list of incoming 404s so we know which URLs to redirect?

**Comment by q0rban** [comment]
Oh, I did however create a custom report in GA to view the 404s (though it's empty right now for the above reason): https://analytics.google.com/analytics/web/#/my-reports/0oD0wLZSS-KGL1Gops-ggg/a69911960w203955541p197439806/

**Comment by bchavet** [comment]
I bet this was mostly a problem because we weren't returning HTTP 404 responses for "not found". There was a reason for that, but I don't remember what it was.

We are now returning legit 404's, so these should be getting pruned from Google's indexes automatically now.
